format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
${custom.caffeinate}\
${custom.savage}\
$fill\
$all\
"""

command_timeout = 500

[aws]
disabled = true

[buf]
disabled = true

[custom.caffeinate]
style = 'bold #6c71c4'
symbol = '  '
when = 'pgrep caffeinate'
disabled = true # No longer used.

# [custom.savage]
# command = 'git grep -EI "SAVAGE\:" | wc -l'
# ignore_timeout = true
# style = 'bold #6c71c4'
# symbol = ' '
# when = 'git grep -EI "SAVAGE\:"'

[directory]
repo_root_style = 'bold purple'
truncation_symbol = ".../"
truncate_to_repo = false
truncation_length = 0

[docker_context]
disabled = true

[fill]
symbol = " "

[gcloud]
disabled = true

[git_branch]
truncation_length = 36

[git_commit]
only_detached = false

[kubernetes]
disabled = false
format = '[$symbol$context( \($namespace\))]($style) '

[nix_shell]
disabled = true

[nodejs]
disabled = true

[python]
disabled = true

[ruby]
disabled = true

[status]
disabled = false
format = '[$symbol $common_meaning $signal_name $int]($style)'
map_symbol = true
pipestatus = false
recognize_signal_code = true
success_symbol = ''

[terraform]
disabled = true
