#!/bin/bash

set -eo pipefail

main() {
  local namespace name key

  for _i in "$@"; do
    case "$1" in
      -n|--namespace)
        namespace="$2"
        shift
        shift
        ;;
      *)
        ;;
    esac
  done

  name="$1"
  key="$2"

  kubectl get secret -n "$namespace" "$name" -o json | jq -r --arg key "$key" '.data[$key] | @base64d'
}

main "$@"
