-- local lspconfig = require("lspconfig")
--
-- lspconfig.golangci_lint_ls.setup({
--   filetypes = { "go", "gomod" },
-- })
--
-- return {
--   "neovim/nvim-lspconfig",
--   opts = {
--     servers = {
--       golangcilsp = {
--         default_config = {
--           cmd = { "golangci-lint-langserver" },
--           root_dir = lspconfig.util.root_pattern(".git", "go.mod"),
--           init_options = {
--             command = {
--               "golangci-lint",
--               "run",
--               -- "--enable-all",
--               -- "--disable",
--               -- "lll",
--               "--out-format",
--               "json",
--               "--issues-exit-code=1",
--             },
--           },
--         },
--       },
--     },
--   },
-- }
return {}
